traj_manager_agent_1:
  ros__parameters:
    robot_name: "robot_1"
    waypoints: [0.0, 0.0, 5.0,  # x y z
                5.0, 5.0, 7.0] #, 
                # 10.0, 00.0, 3.0]
    obstacles: [20.0, 20.0, 20.0]
    obstacle_distance: 0.01

traj_manager_agent_2:
  ros__parameters:
    robot_name: "robot_2"
    waypoints: [0.0, 3.0, 5.0,  # x y z
                5.0, -2.0, 4.0,
                11.0, 3.0, 6.0]
    obstacles: [2.0, 2.0, 5.0]
    obstacle_distance: 0.5

traj_manager_agent_3:
  ros__parameters:
    robot_name: "robot_3"
    waypoints: [1.0, 6.0, 5.0,  # x y z
                7.0, 5.0, 5.0,
                12.0, 0.0, 5.0]
    obstacles: [2.0, 2.0, 5.0]
    obstacle_distance: 0.5


